version: "3.7"
services:
  flask_app:
    build: './flask_app'
    environment:
      - REDIS_URL=redis
      - REDIS_PORT=6379
    ports:
      - "5000:5000"
    depends_on:
      - redis

  simple_worker:
    build: './worker'
    user: nobody
    depends_on:
      - redis
      - flask_app

  redis:
    image: 'redis:4-alpine'
    ports:
      - '6379:6379'

  db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: survey
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306
